### ISSUE TITLE
'Cranberry' Radio Module Daughterboard

### ISSUE THREAD

**Issue by FifoIronton** [LakeMaps/Dartmouth#2]
Need to create a radio module breakout board for RFM9XW. We want:
- RPSMA output
- SPI to microUSB port
- 3.3V linear regulator

**Comment by arandell93** [comment]
Since we need two modules (one on the boat and one on shore), I think we're best making them identical.

Note: We are going to be bringing ONLY a USB cable to these modules. Power will be in the form of 5V via USB, so a USB hub is required to provide enough current.

Any SPI to USB converter chip we get will have to be capable of at least 300 kbit/s

**Comment by arandell93** [comment]
I'm gonna go ahead and make this priority ahead of the motherboard, as I feel this will take the most work to get sorted (config, testing, antenna messing), and it is independent of the motherboard so the latter work can be parallel to the development of the other boards.

**Comment by arandell93** [comment]
Potential SPI to USB converter:
https://www.digikey.ca/product-detail/en/microchip-technology/MCP2210-I-SS/MCP2210-I-SS-ND/2835087
Also available in SMD, but I think this package would be easier to solder to.

**Comment by FifoIronton** [comment]
We wouldn't be able to use the alternate package that they have, as the pads are underneath the chip on that package.

Speaking of that, we should probably aim to get several of the boards done so I can solder and verify them at Solace - the pins on the chip you've shared are only separated by about a millimeter, and Solace much smaller soldering irons than I have access to at MUN. 
I'm not sure if Solace'll let me borrow a key for after hours access during the semester, but I will ask about it closer to the end of my work term.

**Comment by arandell93** [comment]
Yeah that's what I'm thinking. I'll create a tracking issue (#4) for that.

**Comment by FifoIronton** [comment]
First draft of schematic fleshed out as of 8d9b87d601a9ebe1b7e795f87eb9836f95efb3d4 

If you think this looks appropriate I will continue working towards finishing layout ASAP
![cranberryschematic20160731](https://cloud.githubusercontent.com/assets/18233244/17282015/c71145e0-577b-11e6-9b13-18d5e39ff202.jpg)

**Comment by arandell93** [comment]
Are we using any of the IO on the radio module? I see you've got them all connected to the USB-SPI bridge GPIO, but do we know how to get at the GPIO in software via the USB interface?

**Comment by FifoIronton** [comment]
I'll be honest, I haven't actually read the full data sheets for both of them. I'm like 80% sure that the GPIO are controlled by the USB interface, as they'd be needed as for Slave Select (SS) pins for the SPI interface (assuming you're not doing some complex Daisy Chaining thing). 
Based on the LoRa balloon system I've shown you before, the guy connects some of the IOs on that module for selecting options or something in his [software](https://github.com/daveake/LoRaArduinoSerial/blob/master/LoRaArduinoSerial.ino). It's another thing I haven't actually read, but I want to figure out what's going on there

**Comment by FifoIronton** [comment]
Next time let's get the SOIC footprint instead of the SSOP footprint. Wider lead spacing, which is good for me

**Comment by FifoIronton** [comment]
![capture](https://cloud.githubusercontent.com/assets/18233244/17722030/76160bae-6409-11e6-9780-c269b8f32acb.PNG)
Things to be done:
- Change hole sizes
- Put a fun label on?
- make sure it doesn't suck

**Comment by arandell93** [comment]
- Am I correct in understanding that the MCP2210 is underneath the RFM69HCW where the MCP is surface mount on one side and the RFM is through-hole mounted on the other?
  - Side note: We will need pins (what spacing) to mount the RFM through-hole.
- Power LED resistor should be 33 Ohms.

**Comment by FifoIronton** [comment]
Rev1 Schematic of this board
![capture](https://cloud.githubusercontent.com/assets/18233244/19707074/07a8d6f6-9af0-11e6-9601-3d83d83da09a.PNG)
