### ISSUE TITLE
GPS PCB Design

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/Dartmouth#7]
The PCB for the GPS needs the following:
- 6 pin connector for the GPS module
- 5 V Power
- 5 V TTL UART (TX and RX)
- Associated passive components (Caps, etc)
- Power LED

The GPS module is an [EM 406](https://www.sparkfun.com/datasheets/GPS/EM-406%20Product_Guide1.pdf).

**Comment by arandell93** [comment]
Initial Design:
![13933544_10154398645852433_201246617_n](https://cloud.githubusercontent.com/assets/10678515/17577314/9e77146a-5f56-11e6-987c-ce4863f69ad4.png)

**Comment by arandell93** [comment]
### Requires
- Ethernet Port Shield (9) should be grounded.

**Comment by FifoIronton** [comment]
![capture](https://cloud.githubusercontent.com/assets/18233244/17721125/5604feda-6402-11e6-8456-661bd7efc597.PNG)
To Do:
-Change hole diameters to the free holes from APC
-Make the layout eaier to read, even though there won't be any silk screen
-Make sure it doesn't suck

**Comment by arandell93** [comment]
- LED resistor should be 210 ohms.
- Confirm GPS port is correct type (JST SH Vertical [or Horizontal] 6-Pin)
